language: cpp
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-7
    packages:
      - clang-7
      - lld-7
  homebrew:
    taps:
      - facebook/fb
    packages:
      - buck

os:
  - linux

compiler:
  - clang

env:
  - BUCKAROO_VERSION=buckaroo-redux-alpha-11

osx_image: xcode9.3

before_install:
  - ./travis/before-install-$TRAVIS_OS_NAME.sh

script:
  - ./buckaroo-client install
  - buck build -c ui.superconsole=DISABLED cxx.cxxpp=`$CXX` cxx.cxx=`$CXX` //:cppcoro
  - buck run -c ui.superconsole=DISABLED cxx.cxxpp=`$CXX` cxx.cxx=`$CXX` //test:test
